//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST10090990_PART2_APP.ADO.NET_MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public string ModCode { get; set; }
        public string ModName { get; set; }
        public int Credits { get; set; }
        public float Hours { get; set; }
        public int NumWeeks { get; set; }
        public System.DateTime StartDate { get; set; }
        public float SelfStudy { get; set; }
        public float Remainder { get; set; }
        public string Username { get; set; }
    }
}
